language: node_js
matrix:
    include:
        - os: linux
        - os: osx
node_js:
    - 8
cache:
    directories:
        - node_modules
deploy:
    provider: script
    script: npm run pack
    on:
        branch: master
