language: node_js
os: 
  - linux
  - windows
matrix:
  fast_finish: true
  allow_failures:
    - os: windows
cache:
  directories:
    - node_modules
before_install:
  - npm install
after_success:
  - npm run pack