language: node_js
matrix:
  include:
    - os: linux
    - os: osx
    - os: windows
  allow_failures:
    - os: windows
node_js:
    - 8
cache:
    directories:
        - node_modules
before_install:
    - npm run install:client
after_success:
    - npm run pack
