language: node_js
matrix:
    include:
        - os: linux
        - os: osx
node_js:
    - 8
cache:
    directories:
        - node_modules
env:
    - ELECTRON_FORCE_WINDOW_MENU_BAR=true
after_success:
    - if [ $TRAVIS_BRANCH == "master" ]; then npm run pack; fi
