language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then 'stable'; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 'node'; fi
cache:
  directories:
    - node_modules
before_install: 
  - npm run install:client