language: node_js
matrix:
  include:
    - os: linux
    - os: osx
    - os: windows
  allow_failures:
    - os: windows
node_js:
    - 8
cache:
    directories:
        - node_modules
before_install:
    - npm run install:client
script:
    - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm test          ; fi
    - npm run pack
