image: Visual Studio 2017

branches:
    only:
        - master

platform:
    - x64

cache:
    - node_modules
    - '%USERPROFILE%\.electron'

init:
    - git config --global core.autocrlf input

install:
    - ps: Install-Product node 8 x64
    - yarn install

build: off

test_script:
    - yarn test

build_script:
    - yarn run pack

test: on
