name: Release

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - name: Testing the Application
      run:
        npm run test
